### ISSUE TITLE
API requires (unsafe) pushing of secret over network

### ISSUE THREAD

**Issue by marcoalkema** [ShiftNrg/shift-lisk#7]
Hi there,

In light of privacy and safety concerns, it seems to me that pushing a transaction containing an account's secret can lead to accounts being hijacked. 

I was wondering if there are any plans on making this process safer for users?

**Comment by mswezey23** [comment]
I assume you're referring to this API doc located [here](https://github.com/ShiftNrg/API_Documentation#send-transaction)?
I would only recommend using that API if you're targeting your own node. 

For people that do not have their own nodes...I did some digging. Using the `https://wallet.shiftnrg.org` web app; it actually signs transactions client side. (thankfully!)
References:
**Signing the TX**
https://github.com/ShiftNrg/shift-wallet/blob/be99f144cf030dd1a69bd19bcb55c685a3a091cf/js/controllers/modals/sendTransactionController.js#L232

**JS Lib** 
https://github.com/ShiftNrg/shift-js/blob/d7d35e005cc0814a6a7463452551f31a337f4ac6/lib/transactions/transaction.js#L47

Nano wallet looks like it actually sends the secrets in the POST request! YIKES! 
Luckily the domains that it connects to are known and in control. But yet, this isn't a very good model to trust. 
I can only recommend people using the `nano wallet` when connecting to their own nodes. Hopefully on localhost or on a home network behind a router.

**Comment by mswezey23** [comment]
Update: 
kwell mentioned a comment which made me re-look at the Nano Wallet. 

The Nano Wallet actually does sign client side before transmitting the transaction! 
Initial code that made me think it didn't:
https://github.com/ShiftNrg/shift-nano/blob/f3397ddce7e2a7d00b8fa10f8d41ed3d536db26f/src/utils/api/peers.js#L7

Code that signs the transaction before submitting: 
https://github.com/ShiftNrg/shift-js/blob/d7d35e005cc0814a6a7463452551f31a337f4ac6/lib/api/parseTransaction.js#L157

With that. Here's my updated findings:

1) Web Wallet is safe to use given the user's own computer is not compromised.
2) The Nano Wallet is safe to use given the user's own computer is not compromised. 
3) The API should only be used against your own node on a secured network on a secure server
4) Points 1 & 2 assume the domain, DNS, and server side master nodes are secured

There's another way to generate offline transactions that community member shared:
Linke here: 
https://github.com/samuelpaulsun/offlineShiftWebsite

With the old chain going away - I don't see the need currently at this stage to improve the API. 
Closing this issue as the result.
